### ISSUE TITLE
how to fix "ebpf_initialization_failed"

### ISSUE THREAD

**Issue by hikaruxxo** [ntop/libebpfflow#12]
hi, i have downloaded the newest libebpfflow , and install bcc 0.80.
but when i ran the ./ebpflowexport , i caught this error:

./ebpflowexport: /lib64/libldap_r-2.4.so.2: no version information available (required by /usr/local/lib/libcurl.so.4)
Welcome to ebpflowexport v.1.0.191103
(C) 2018-19 ntop.org
Initializing eBPF [Legacy API]...
In file included from <built-in>:2:
/virtual/include/bcc/bpf.h:13:10: fatal error: 'linux/bpf_common.h' file not
      found
#include <linux/bpf_common.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
Unable to initialize libebpfflow: ebpf_initialization_failed
eBPF terminated

**Comment by samuelesabella** [comment]
Hi hikaruxxo. Can you give me some details about the distribution that you are using and the version, please?

**Comment by hikaruxxo** [comment]
[root@master libebpfflow-master]# lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.7.1908 (Core)
Release:	7.7.1908
Codename:	Core


[root@master libebpfflow-master]# yum list installed |grep bcc
bcc.x86_64                            0.8.0-1.el7                @base          
bcc-devel.x86_64                      0.8.0-1.el7                @base          
bcc-tools.x86_64                      0.8.0-1.el7                @base          
python-bcc.x86_64                     0.8.0-1.el7                @base 


any others you need?

**Comment by lucaderi** [comment]
Hello, this is our system. Can you please check what are the differences with yours?

deri@centos7 202> rpm -qa|grep bcc
python-bcc-0.8.0-1.el7.x86_64
bcc-tools-0.8.0-1.el7.x86_64
bcc-devel-0.8.0-1.el7.x86_64
bcc-0.8.0-1.el7.x86_64

deri@centos7 208> lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.7.1908 (Core)
Release:	7.7.1908
Codename:	Core

deri@centos7 206> sudo ./ebpflowexport -v
Welcome to ebpflowexport v.1.0.191104
(C) 2018-19 ntop.org
Initializing eBPF [Legacy API]...
eBPF initializated successfully
* Terminating * 
eBPF terminated
deri@centos7 207> uname -a
Linux centos7.ntop.org 3.10.0-1062.1.1.el7.x86_64 #1 SMP Fri Sep 13 22:55:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by hikaruxxo** [comment]
it seems to make no difference.
is it related to kernel compilation options?

**Comment by faustothegrey** [comment]
Hi,
I'm trying to use **libebpfflow** on **ubuntu 19.10 ( eoan ermine )**. I'm able to compile but
when I try to execute ebpflowexport (sudo ./ebpflowexport -tio) I get the same  general error 
"ebpf_initialization_failed" due to several compilation errors (12 errors total).
Any clues why this could happen ?  Thanks in advance. Fausto.

Welcome to ebpflowexport v.1.0.191118
(C) 2018-19 ntop.org
Initializing eBPF [Legacy API]...
In file included from /virtual/main.c:22:
In file included from include/net/sock.h:46:
In file included from include/linux/netdevice.h:42:
In file included from include/net/netprio_cgroup.h:11:
In file included from include/linux/cgroup.h:28:
In file included from include/linux/cgroup-defs.h:22:
In file included from include/linux/bpf-cgroup.h:5:
include/linux/bpf.h:115:3: error: variable has incomplete type 'struct bpf_spin_lock'
                (struct bpf_spin_lock){};
                ^~~~~~~~~~~~~~~~~~~~~~~~
include/linux/bpf.h:114:11: note: forward declaration of 'struct bpf_spin_lock'
        *(struct bpf_spin_lock *)(dst + map->spin_lock_off) =
                 ^
include/linux/bpf.h:125:22: error: invalid application of 'sizeof' to an incomplete type 'struct bpf_spin_lock'
                memcpy(dst + off + sizeof(struct bpf_spin_lock),
                                   ^     ~~~~~~~~~~~~~~~~~~~~~~
include/linux/bpf.h:125:36: note: forward declaration of 'struct bpf_spin_lock'
                memcpy(dst + off + sizeof(struct bpf_spin_lock),
                                                 ^
include/linux/bpf.h:126:22: error: invalid application of 'sizeof' to an incomplete type 'struct bpf_spin_lock'
                       src + off + sizeof(struct bpf_spin_lock),
                                   ^     ~~~~~~~~~~~~~~~~~~~~~~
include/linux/bpf.h:125:36: note: forward declaration of 'struct bpf_spin_lock'
                memcpy(dst + off + sizeof(struct bpf_spin_lock),
                                                 ^
include/linux/bpf.h:127:34: error: invalid application of 'sizeof' to an incomplete type 'struct bpf_spin_lock'
                       map->value_size - off - sizeof(struct bpf_spin_lock));
                                               ^     ~~~~~~~~~~~~~~~~~~~~~~
include/linux/bpf.h:125:36: note: forward declaration of 'struct bpf_spin_lock'
                memcpy(dst + off + sizeof(struct bpf_spin_lock),
                                                 ^
include/linux/bpf.h:454:39: error: use of undeclared identifier 'BPF_F_RDONLY_PROG'
        u32 access_flags = map->map_flags & (BPF_F_RDONLY_PROG | BPF_F_WRONLY_PROG);
                                             ^
include/linux/bpf.h:454:59: error: use of undeclared identifier 'BPF_F_WRONLY_PROG'
        u32 access_flags = map->map_flags & (BPF_F_RDONLY_PROG | BPF_F_WRONLY_PROG);
                                                                 ^
include/linux/bpf.h:459:21: error: use of undeclared identifier 'BPF_F_RDONLY_PROG'
        if (access_flags & BPF_F_RDONLY_PROG)
                           ^
include/linux/bpf.h:461:26: error: use of undeclared identifier 'BPF_F_WRONLY_PROG'
        else if (access_flags & BPF_F_WRONLY_PROG)
                                ^
include/linux/bpf.h:469:26: error: use of undeclared identifier 'BPF_F_RDONLY_PROG'
        return (access_flags & (BPF_F_RDONLY_PROG | BPF_F_WRONLY_PROG)) !=
                                ^
include/linux/bpf.h:469:46: error: use of undeclared identifier 'BPF_F_WRONLY_PROG'
        return (access_flags & (BPF_F_RDONLY_PROG | BPF_F_WRONLY_PROG)) !=
                                                    ^
include/linux/bpf.h:470:10: error: use of undeclared identifier 'BPF_F_RDONLY_PROG'
               (BPF_F_RDONLY_PROG | BPF_F_WRONLY_PROG);
                ^
include/linux/bpf.h:470:30: error: use of undeclared identifier 'BPF_F_WRONLY_PROG'
               (BPF_F_RDONLY_PROG | BPF_F_WRONLY_PROG);

- - - - - - - -   omissis   

49 warnings and 12 errors generated.
Unable to initialize libebpfflow: ebpf_initialization_failed
eBPF terminated

**Comment by lucaderi** [comment]
On Ubuntu 18.04 and 20.04 everything works. I suggest to move to a LTS edition as eBPF is not yet stable across all distributions
